AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI Lambda functions for DynamoDB and S3 operations

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 256
    Environment:
      Variables:
        AWS_DEFAULT_REGION: !Ref AWS::Region

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  
  BucketOwner:
    Type: String
    Description: AWS Account ID for bucket ownership verification (optional)
    Default: ""

Resources:
  # DynamoDB Table
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-ItemsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket
  FilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Environment}-files-bucket-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Lambda Execution Role for DynamoDB Function
  DynamoDBLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt ItemsTable.Arn

  # Lambda Execution Role for S3 Function
  S3LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt FilesBucket.Arn
                  - !Sub ${FilesBucket.Arn}/*

  # DynamoDB Lambda Function
  DynamoDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-dynamodb-api
      CodeUri: lambda-dynamo/
      Handler: app.handler
      Role: !GetAtt DynamoDBLambdaRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Events:
        CreateItem:
          Type: Api
          Properties:
            Path: /items
            Method: POST
            RestApiId: !Ref ApiGateway
        UpdateItem:
          Type: Api
          Properties:
            Path: /items/{item_id}
            Method: PUT
            RestApiId: !Ref ApiGateway

  # S3 Lambda Function
  S3Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-s3-api
      CodeUri: lambda-s3/
      Handler: app.handler
      Role: !GetAtt S3LambdaRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref FilesBucket
          BUCKET_OWNER: !If [HasBucketOwner, !Ref BucketOwner, !Ref AWS::NoValue]
      Events:
        GetFile:
          Type: Api
          Properties:
            Path: /files/{file_key+}
            Method: GET
            RestApiId: !Ref ApiGateway

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${Environment}-fastapi-gateway
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      TracingEnabled: true
      Tags:
        Environment: !Ref Environment

Conditions:
  HasBucketOwner: !Not [!Equals [!Ref BucketOwner, ""]]

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/
    Export:
      Name: !Sub ${Environment}-ApiUrl

  DynamoDBFunctionArn:
    Description: DynamoDB Lambda Function ARN
    Value: !GetAtt DynamoDBFunction.Arn
    Export:
      Name: !Sub ${Environment}-DynamoDBFunctionArn

  S3FunctionArn:
    Description: S3 Lambda Function ARN
    Value: !GetAtt S3Function.Arn
    Export:
      Name: !Sub ${Environment}-S3FunctionArn

  ItemsTableName:
    Description: DynamoDB table name
    Value: !Ref ItemsTable
    Export:
      Name: !Sub ${Environment}-ItemsTableName

  FilesBucketName:
    Description: S3 bucket name
    Value: !Ref FilesBucket
    Export:
      Name: !Sub ${Environment}-FilesBucketName
